---
title: "p8105_hw5_yq2251"
author: "TritonD"
date: "11/5/2019"
output: github_document
---

```{r}
library(readxl)
library(tidyverse)
library(stringr)
library(tidyr)
```


## question 1 Writing function
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```


```{r}
no_missing=function(x){
  if(is.numeric(x))   
    {x[is.na(x)]=mean(x,na.rm=TRUE)}
  else if (!is.numeric(x))
    {x[is.na(x)]="virginica"}
  
  x}
```

output with the function
```{r}
output=map_dfr(iris_with_missing,no_missing)
```


## question 2 create  tidy dataframe

```{r}
allfiles=list.files(path="./data")%>%
  substr(1,6)
```

```{r}
df= tibble(allfiles = list.files(path="./data"),
    path = str_c("./data/", allfiles))%>%
  mutate(obs_time = map(path, read_csv),)%>%
  unnest()%>%
  
  select(-path)%>%
  mutate(arm = substr(allfiles, 1, 3),
         arm = recode(arm, "con" = "Control", "exp" = "Experiment"),
    subject_id=substr(allfiles,5,6),
    subject_id=as.numeric(subject_id))%>%
  
  pivot_longer(week_1:week_8,
    names_to = "week",
    values_to = "obs" )%>%
  
  mutate(week=substr(week, 6,7), week=as.numeric(week))%>%
  select(-allfiles)
```

## making spaghetti plot
```{r}
df%>%
  ggplot(aes(x = week, y = obs, color=subject_id,group= subject_id)）+
  geom_line() +facet_grid(. ~arm) +
   labs(title = "Observations on individual subjects",
    x = "week",
    y = "observations"
  ) 
```

In the experiment group, as time goes, there is a visible increasing trend in individual subjects. The control group is more stable without much difference.


## question 3 regression model
```{r}
sim_regression = function(n=30, sigma=50, beta0 = 2, beta1 = 0) {
  
  sim_data = tibble(
    xi1 = rnorm(n, mean = 0, sd = 1),
    yi = beta0 + beta1 * xi1 + rnorm(n, 0, sigma)
  )
  
  ls_fit = lm(yi ~ xi1, data = sim_data)
  
  tibble(
    p_value = broom::tidy(ls_fit)$p.value[2],
    beta1_hat = broom::tidy(ls_fit)$estimate[2],
    alpha=0.05
  )
}
```


# Generate 10000 datasets
```{r}
sim_results1 = 
  rerun(10000, sim_regression(30, 2, 0)) %>% 
  bind_rows()
```

# make a list for 6 beta1
```{r}
beta1s=list("beta1_1"=1,"beta1_2"=2,"beta1_3"=3, "beta1_4"=4,"beta1_5"=5,"beta1_6"=6)
output = vector("list", 6)

for (i in 1:6) {
  output[[i]] = rerun(10000, sim_regression(beta1s[[i]])) %>% 
    bind_rows
}
```

```{r}
sim_results2 = 
  tibble(beta1 = c(1,2,3,4,5,6)) %>% 
  mutate(
    output_lists = map(.x = beta1, ~rerun(10000, sim_regression(beta1 = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)
```

```{r}
  sim_results2%>%
  group_by(beta1)%>%
  mutate(
    power_test=sum(p_value<0.05)/10000
    ) %>% 
  ungroup()%>%
  ggplot(aes(x = beta1, y = power_test, color=beta1)) + 
  geom_point()+geom_line()+
  labs(
    title = "Association between Effect size and Power in regression",
    x = "effect size",
    y = "power"
  ) 
```
```

